In [ ]:
!pip install numpy

In [ ]:
import numpy
numpy.arange(4)

array([0, 1, 2, 3])

In [ ]:
#Scalar => Refers to single numeric value

#Vectors => Refers to a 1 Dimension like either row or column

'''Row vector->  Having only one row'''

'''Column vector-> having  only one column'''

#Matrix -=> Refera to 2D array having rows and colums

In [ ]:
import numpy
arr=numpy.arange(4)
print(arr)
arr+3
print(arr)

[0 1 2 3]
[0 1 2 3]


In [ ]:
import numpy as np
arr=np.arange(4)
arr.size  #No. of elements
arr.shape #Tells the number of rows or column
print("Orignal=>",arr)
arr[0]=10
print("After changing=>",arr)

Orignal=> [0 1 2 3]
After changing=> [10  1  2  3]


In [ ]:
import numpy as np
arr=np.array([10,20,30])
arr1=np.array([[10,20,30]])   #Row Vector
print(arr.shape,arr1.shape)

(3,) (1, 3)


In [ ]:
import numpy as np
arr1=np.array([[10,20,30],
              [40,50,60]])
print(arr1.shape)
print(arr1)

arr1=arr1.reshape((3,2))  #Reshape=> converts the matrix as described
print(arr1)

(2, 3)
[[10 20 30]
 [40 50 60]]
[[10 20]
 [30 40]
 [50 60]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3],
               [4,5,3],
               [7,8,9],
             [10,11,12]])

print(arr.shape)
print("\nOrgnal matrix\n")

print(arr)


arr=arr.reshape(3,4)
print("\nAfter Modifying\n")

print(arr)

(4, 3)

Orgnal matrix

[[ 1  2  3]
 [ 4  5  3]
 [ 7  8  9]
 [10 11 12]]

After Modifying

[[ 1  2  3  4]
 [ 5  3  7  8]
 [ 9 10 11 12]]


In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr1=np.arange(10,dtype="float")

arr1=arr1.reshape(5,2)
arr1
np.ones_like(arr1)  #Gives ones array of the given matrix size

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
arr=np.eye((3))   #Identical array
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#SLICING & INDEXING

In [ ]:
import numpy as np
arr=np.array([[10,20,30],
              [40,50,60]])

print(arr[1][2])  #first value is row & second is column

print(arr[:,1]) #All rows and column 1

print(arr[0:,1:]) #First two rows and column 1 onwards

60
[20 50]
[[20 30]
 [50 60]]


In [ ]:
import numpy as np
arr=np.array([[10,20,30],
              [40,50,60]])

print(arr[:,0:2].flatten()) #Flatten converts 2D to 1D array

[10 20 40 50]


In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr)
arr[arr>25]   #Filtering the data

[[10 20 30]
 [40 50 60]]


array([30, 40, 50, 60])

In [ ]:
arr=np.array([[10,20,30],[40,50,60]])
arr[(arr>25)&(arr<50)]  #Double Filtering

array([30, 40])

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
add=a+b
print("add=>",add)  #Element wise addition
mul=a*b
print("mul=>",mul)
sub=a-b
print("sub=>",sub)
dot=a.dot(b) #Dot product gives a multiplication+addition
print("dot product=>",dot)

add=> [5 7 9]
mul=> [ 4 10 18]
sub=> [-3 -3 -3]
dot product=> 32


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([2,4,6])
print(a.dot(b))

[28 64]


In [ ]:
a=np.array([[1,2],[4,5],[1,2]])
b=np.array([[10,20,30],[50,100,200]])
print(a.dot(b))

[[ 110  220  430]
 [ 290  580 1120]
 [ 110  220  430]]


In [84]:
#Aggregate function
data=np.array([[1,2],[3,4]])
sum=np.sum(data)
print(sum)
mean=np.mean(data)
print(mean)
min=np.min(data,axis=0)   #axis=0 column
print(min)
max=np.max(data,axis=1)   #axis=1 rows
print(max)

10
2.5
[1 2]
[2 4]


In [89]:
data=np.array([[1,2,5],[3,4,2]])
max=np.max(data,axis=1)
print(max)

[5 4]


In [90]:
x=np.array([[1,2],
            [3,4]])
y=np.array([[5,6]])
np.vstack((x,y))    #Vertical Stacking


array([[1, 2],
       [3, 4],
       [5, 6]])

In [92]:
x=np.array([[1,2],
            [3,4]])
y=np.array([[5,6],
            [7,8]])
np.hstack((x,y))  #Horizontal Stacking

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])